name: Build MovieAssistant

on: [push]

jobs:
  Build_MovieAssistant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build MovieAssistant_WinForm_Win
